config/routes.rb
Rails.application.routes.draw do
  root to: "lists#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :lists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
  has_many :items

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  def index
    @lists = List.all.reverse
  end

  def show
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      respond_to do |format|
        format.html { redirect_to lists_path, notice: 'List successfully created.' }
        format.turbo_stream { flash.now[:notice] = 'List successfully created.' }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @list.update(list_params)
      respond_to do |format|
        format.html { redirect_to lists_path, notice: 'List successfully edited.' }
        format.turbo_stream { flash.now[:notice] = 'List successfully edited.' }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy

    respond_to do |format|
      format.html { redirect_to lists_path }
      format.turbo_stream { flash.now[:notice] = 'List successfully destroyed.' }
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |_, message| %>
  <p><%= message %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSandbox</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with model: @list do |form| %>
  <div class='mx-5 my-5'>
    <%= form.label :name %>
    <%= form.text_field :name %>
    <%= form.submit %>
  </div>
<% end %>

app/views/lists/_list.html.erb
<%= turbo_frame_tag "whole_list_#{list.id}" do %>
  <div class='my-8 mx-5 border-solid border-2 p-2 border-black'>
    <%= turbo_frame_tag list do %>
      <h1 class='text-2xl'><%= link_to list.name, list_path(list), data: {turbo_frame: "_top"} %></h1>

      <%= link_to 'Edit list name', edit_list_path(list)%>
    <% end %>

    <%= button_to 'Remove list', list_path(list), method: :delete %>

    <ul>
      <% list.items.each do |item| %>
        <li><%= item.title %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/lists/create.turbo_stream.erb
<%= turbo_stream.prepend 'lists', @list %>
<%= turbo_stream.update List.new, "" %>
<%= turbo_stream.prepend 'flash', partial: 'layouts/flash' %>

app/views/lists/destroy.turbo_stream.erb
<%= turbo_stream.remove "whole_list_#{@list.id}" %>
<%= turbo_stream.prepend 'flash', partial: 'layouts/flash' %>

app/views/lists/edit.html.erb
<h1>Edit new list</h1>

<%= turbo_frame_tag @list do %>
  <%= render 'form', list: @list %>
<% end %>

app/views/lists/index.html.erb
<h1 class='my-8 mx-5 text-5xl'>This is all your todos</h1>

<div id='flash' class='my-8 mx-5 text-md border-solid border-1 border-black'>
  <%= render 'layouts/flash' %>
</div>

<%= link_to 'New list', new_list_path,
  data: {turbo_frame: dom_id(List.new)},
  class: 'text-lg border-solid border-2 border-black p-2 mx-5'
  %>

<%= turbo_frame_tag List.new %>

<%= turbo_frame_tag 'lists' do %>
  <%= render @lists %>
<% end %>

app/views/lists/new.html.erb
<h1 class='my-8 mx-5 text-2xl'>Create new list</h1>

<%= turbo_frame_tag List.new do %>
  <%= render 'form', list: @list %>
<% end %>

app/views/lists/show.html.erb
<%= render 'lists/list', list: @list %>

app/views/lists/update.turbo_stream.erb
<%= turbo_stream.replace "whole_list_#{@list.id}", partial: 'lists/list', locals: {list: @list} %>
<%= turbo_stream.prepend 'flash', partial: 'layouts/flash' %>